export const englishLayout = [
  [
    "`",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "Backspace",
  ],
  ["Tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]", "\\"],
  ["CapsLock", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "'", "Enter"],
  ["shiftl", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "shiftr"],
  ["hebrew", "emoji", "Space", ".com", "@"],
];
export const englishLayoutUpperCase = [
  [
    "`",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "Backspace",
  ],
  ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "[", "]", "\\"],
  ["CapsLock", "A", "S", "D", "F", "G", "H", "J", "K", "L", ";", "'", "Enter"],
  ["shiftl", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/", "shiftr"],
  ["hebrew", "emoji", "Space", ".com", "@"],
];
export const hebrewLayout = [
  [
    "`",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "Backspace",
  ],
  ["Tab", "/", "'", "ק", "ר", "א", "ט", "ו", "י", "ם", "פ", "]", "[", "\\"],
  ["CapsLock", "ש", "ד", "ג", "כ", "ע", "י", "ח", "ל", "ך", "ף", ",", "Enter"],
  ["shiftl", "ז", "ס", "ב", "ה", "נ", "מ", "צ", "ת", "ץ", ".", "shiftr"],
  ["English", "emoji", "Space", ".com", "@"],
];

export const emojiList1 = [
  [
    "\uD83D\uDE00",
    "\uD83D\uDE01",
    "\uD83D\uDE02",
    "\uD83E\uDD23",
    "\uD83D\uDE03",
    "\uD83D\uDE04",
    "\uD83D\uDE05",
    "\uD83D\uDE06",
    "\uD83D\uDE09",
    "\uD83D\uDE0A",
  ],
  [
    "\uD83D\uDE0B",
    "\uD83D\uDE0E",
    "\uD83D\uDE0D",
    "\uD83D\uDE18",
    "\uD83D\uDE1A",
    "\uD83D\uDE1C",
    "\uD83D\uDE1B",
    "\uD83E\uDD11",
    "\uD83E\uDD17",
    "\uD83E\uDD14",
  ],
  [
    "\uD83E\uDD10",
    "\uD83E\uDD28",
    "\uD83D\uDE10",
    "\uD83D\uDE11",
    "\uD83D\uDE12",
    "\uD83D\uDE0F",
    "\uD83D\uDE12",
    "\uD83E\uDD37",
    "\uD83D\uDE2C",
    "\uD83D\uDE22",
  ],
  [
    "\uD83D\uDE13",
    "\uD83D\uDE2D",
    "\uD83D\uDE34",
    "\uD83D\uDE37",
    "\uD83D\uDE32",
    "\uD83D\uDE35",
    "\uD83D\uDE33",
    "\uD83D\uDE20",
    "\uD83D\uDE21",
    "\uD83D\uDE08",
  ],
  [
    "\uD83D\uDE0C",
    "\uD83D\uDE40",
    "\uD83D\uDC80",
    "\u2620",
    "\uD83D\uDC7D",
    "\uD83D\uDC7E",
    "\uD83E\uDD16",
    "\uD83D\uDCA9",
    "\uD83D\uDC4D",
    "\uD83D\uDC4E",
  ],
  [
    "\uD83D\uDC4C",
    "\uD83E\uDD1F",
    "\uD83E\uDD1E",
    "\uD83E\uDD18",
    "\uD83E\uDD12",
    "\u270C",
    "\uD83E\uDD1C",
    "\uD83E\uDD1D",
    "\uD83E\uDD1B",
    "\uD83E\uDD1A",
    "\uD83D\uDC4B",
  ],
  [
    "\uD83D\uDC4F",
    "\uD83E\uDD90",
    "\u270B",
    "\uD83E\uDD1A",
    "\uD83E\uDD1F",
    "\uD83E\uDD1B",
    "\uD83E\uDD1F",
    "\uD83E\uDD18",
    "\uD83E\uDD0F",
    "\uD83D\uDC4B",
    "\uD83E\uDD19",
  ],
  [
    "\u270A",
    "\uD83E\uDD1E",
    "\uD83E\uDD1C",
    "\uD83D\uDC4F",
    "\uD83D\uDC4A",
    "\uD83D\uDC4C",
    "\uD83D\uDC4F",
    "\uD83D\uDC4D",
    "\uD83D\uDC4E",
    "\u270D",
    "\uD83D\uDC85",
  ],
  [
    "\uD83E\uDD85",
    "\uD83D\uDCBB",
    "\uD83D\uDE4A",
    "\uD83D\uDE48",
    "\uD83D\uDE49",
    "\uD83D\uDE47",
  ],
];
export const emojiList = [
  [
    "😀",
    "😁",
    "😂",
    "🤣",
    "😃",
    "😄",
    "😅",
    "😆",
    "😉",
    "😊",
    "😋",
    "😎",
    "😍",
  ],
  [
    "😘",
    "😜",
    "😝",
    "😛",
    "🤑",
    "🤗",
    "🤔",
    "🤐",
    "🤨",
    "😐",
    "😑",
    "😶",
    "😏",
    "😒",
  ],
  [
    "🙄",
    "😬",
    "😌",
    "😔",
    "😪",
    "😴",
    "😷",
    "🤒",
    "🤕",
    "🤢",
    "🤮",
    "🤧",
    "😈",
  ],
  [
    "👿",
    "👻",
    "💀",
    "☠️",
    "👽",
    "👾",
    "🤖",
    "💩",
    "👍",
    "👎",
    "👌",
    "🤏",
    "✌️",
  ],
  [
    "🤞",
    "🤟",
    "🤘",
    "🤙",
    "👋",
    "🤚",
    "🖐️",
    "✋",
    "👊",
    "🤛",
    "🤜",
    "👏",
    "🙌",
  ],
  [
    "👐",
    "🤲",
    "🙏",
    "✍️",
    "💅",
    "🤳",
    "💪",
    "🦾",
    "🦵",
    "🦶",
    "👂",
    "🦻",
    "👃",
  ],
  "🧠",
  [
    "🦷",
    "🦴",
    "👀",
    "👁️",
    "👅",
    "👄",
    "👶",
    "🧒",
    "👦",
    "👧",
    "🧑",
    "👱",
    "👨",
  ],
  [
    "🧔",
    "👩",
    "👱‍♀️",
    "👩‍🦰",
    "👩‍🦱",
    "👩‍🦳",
    "👩‍🦲",
    "👱‍♂️",
    "👨‍🦰",
    "👨‍🦱",
    "👨‍🦳",
    "👨‍🦲",
    "🧓",
  ],
  [
    "👴",
    "👵",
    "🙍‍♂️",
    "🙍‍♀️",
    "🙎‍♂️",
    "🙎‍♀️",
    "🙅‍♂️",
    "🙅‍♀️",
    "🙆‍♂️",
    "🙆‍♀️",
    "💁‍♂️",
    "💁‍♀️",
    "🙋‍♂️",
  ],
];

export const keyClasses = {
  "`": "width6",
  1: "width6",
  2: "width6",
  3: "width6",
  4: "width6",
  5: "width6",
  6: "width6",
  7: "width6",
  8: "width6",
  9: "width6",
  0: "width6",
  "-": "width6",
  "=": "width6",
  Backspace: "width10",
  Tab: "width10",
  q: "width6",
  w: "width6",
  e: "width6",
  r: "width6",
  t: "width6",
  y: "width6",
  u: "width6",
  i: "width6",
  o: "width6",
  p: "width6",
  "[": "width6",
  "]": "width6",
  "\\": "width6",
  CapsLock: "width12",
  a: "width6",
  s: "width6",
  d: "width6",
  f: "width6",
  g: "width6",
  h: "width6",
  j: "width6",
  k: "width6",
  l: "width6",
  ";": "width6",
  "'": "width6",
  Enter: "width10",
  shiftl: "width14",
  z: "width6",
  x: "width6",
  c: "width6",
  v: "width6",
  b: "width6",
  n: "width6",
  m: "width6",
  ",": "width6",
  ".": "width6",
  "/": "width6",
  shiftr: "width14",
  hebrew: "width20",
  ".com": "width14",
  "@": "width14",
  Space: "width40",
  Q: "width6",
  W: "width6",
  E: "width6",
  R: "width6",
  T: "width6",
  Y: "width6",
  U: "width6",
  I: "width6",
  O: "width6",
  P: "width6",
  A: "width6",
  S: "width6",
  D: "width6",
  F: "width6",
  G: "width6",
  H: "width6",
  J: "width6",
  K: "width6",
  L: "width6",
  Z: "width6",
  X: "width6",
  C: "width6",
  V: "width6",
  B: "width6",
  N: "width6",
  M: "width6",
  English: "width20",
  emoji: "width14",
  ק: "width6",
  ר: "width6",
  א: "width6",
  ט: "width6",
  ו: "width6",
  ן: "width6",
  ם: "width6",
  פ: "width6",
  ש: "width6",
  ד: "width6",
  ג: "width6",
  כ: "width6",
  ע: "width6",
  י: "width6",
  ח: "width6",
  ל: "width6",
  ך: "width6",
  ף: "width6",
  ז: "width6",
  ס: "width6",
  ב: "width6",
  ה: "width6",
  נ: "width6",
  מ: "width6",
  צ: "width6",
  ת: "width6",
  ץ: "width6",
};
