export const englishLayout = [
  [
    "`",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "Backspace",
  ],
  ["Tab", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]", "\\"],
  ["CapsLock", "a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "'", "Enter"],
  ["shiftl", "z", "x", "c", "v", "b", "n", "m", ",", ".", "/", "shiftr"],
  ["hebrew", ".com", "@", "Space"],
];
export const englishLayoutUpperCase = [
  [
    "`",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "Backspace",
  ],
  ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "[", "]", "\\"],
  ["CapsLock", "A", "S", "D", "F", "G", "H", "J", "K", "L", ";", "'", "Enter"],
  ["shiftl", "Z", "X", "C", "V", "B", "N", "M", ",", ".", "/", "shiftr"],
  ["hebrew", ".com", "@", "Space"],
];
export const hebrewLayout = [
  [
    "`",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "-",
    "=",
    "Backspace",
  ],
  ["Tab", "/", "'", "ק", "ר", "א", "ט", "ו", "י", "פ", "]", "[", "\\"],
  ["CapsLock", "ש", "ד", "ג", "כ", "ע", "י", "ח", "ל", "ך", "ף", ",", "Enter"],
  ["ShiftL", "ז", "ס", "ב", "ה", "נ", "מ", "צ", "ת", "ץ", ".", "ShiftR"],
  ["English", ".com", "@", "Space"],
];
